spring:
  cloud:
    config:
      enabled: true
    services:
      registrationMethod: route
eureka:
  client:
    enabled: true
zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    simple:
      path: /simple/**
#uncomment this line and comment the line below when running the application locally      
#      url: http://localhost:8081 
      serviceId: simple-service
#simple:
#  ribbon:
#    DeploymentContextBasedVipAddresses: simple-service

#ribbon:
#  ConnectTimeout: 30000
#  ReadTimeout: 10000
#  maxAutoRetries: 1
#  MaxAutoRetriesNextServer: 2
#  eureka:
#    enabled: true
#
##disable registering with eureka when running locally
#eureka:
#  client:
#    enabled: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
